---
 - name: Logical Operators
   hosts: localhost
   gather_facts: false
   vars:
     x: 10
     y: 15
     list: [10,20,30]
   tasks:
     - debug:
         msg:
          - "The value of x is {{ x }} and the value of y is {{ y }}"
          - "Our list contains: {{ list }}"
          - "x < y and x in list: {{ x < y and x in list }}" - "x > y and x in list: {{ x > y and x in list }}"
          - "x in list or y in list: {{ x in list or y in list }}"
