---
 - name: Data Manipulation
   hosts: localhost
   gather_facts: false
   vars:
     first_name: Bhasker
   tasks:
   - name: Print message
     debug:
       msg:
        - "My name is {{ first_name }} {{ last_name }}"
